# Generated by Django 5.2.7 on 2025-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deactivated_reason",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
