# Generated by Django 5.2.7 on 2025-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_userprofile_deactivated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
